
```{r load_libraries}

library(tidyverse)

library(tidymodels)

library(here)

library(vip)

```



```{r import_data}

data = here("data", "train.csv") %>% 
  read_csv() %>% 
  rename_all(tolower)



```

```{r split_test_train}

data_split = initial_split(data)

train = training(data_split)

```

```{r preprocess}

logit_rec = recipe(survived ~ sex + pclass + age + sibsp + parch,
                   data = train) %>%
  step_mutate(survived = factor(survived, levels = c(0,1))) %>%
  step_mutate(pclass = factor(pclass)) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_normalize(all_numeric_predictors())


# temp_data = logit_rec %>%
#   prep() %>%
#   bake(new_data = NULL)

```

```{r model}

logit_mod = logistic_reg() %>% 
  set_mode("classification") %>% 
  set_engine("glm")

```

```{r fit_model}

logit_wf_fit = workflow() %>% 
  add_recipe(logit_rec) %>% 
  add_model(logit_mod) %>%
  fit(train)


```

```{r f}

logit_wf_fit %>% 
  extract_fit_parsnip() %>% 
  tidy() %>%
  filter(!term == "(Intercept)") %>%
  ggplot(aes(x = reorder(term, abs(estimate)), y = estimate)) +
  geom_col() +
  coord_flip() +
  xlab("Variable") + ylab("Coefficient") + ggtitle("Variable importance")



```

